stages:
  - build
  - test

build:
  stage: build
  image: adoptopenjdk:17-jdk-hotspot
  script:
    - cd university-booking-bot
    - mvn clean compile

test:
  stage: test
  image: adoptopenjdk:17-jdk-hotspot
  script:
    - cd university-booking-bot
    - mvn test