# .gitlab-ci.yml (for GitLab CI/CD)
# This script assumes you're using GitLab CI/CD, but you can adapt it for other CI/CD platforms.

stages:
  - build
  - test

build:
  stage: build
  image: maven:3.8.3-openjdk-17-slim
  script:
    - cd university-booking-bot
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:3.8.3-openjdk-17-slim
  script:
    - cd university-booking-bot
    - mvn test

