stages:
  - build
  - test

build:
  stage: build
  image: openjdk:17-jdk
  script:
    - apt-get update -y
    - apt-get install -y maven
    - cd university-booking-bot
    - mvn clean compile

test:
  stage: test
  image: openjdk:17-jdk
  script:
    - apt-get update -y
    - apt-get install -y maven
    - cd university-booking-bot
    - mvn test
