stages:
  - build
  - test

build:
  stage: build
  image: maven:3.8.4-jdk-11
  script:
    - mvn clean compile --file /university-booking-bot/pom.xml

test:
  stage: test
  image: maven:3.8.4-jdk-11
  script:
    - mvn test --file /university-booking-bot/pom.xml
