name: CI/CD

#env:
#  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#  SONAR_HOST_URL: "localhost:9000"

on:
  push:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    container:
      image: maven:3.8.3-openjdk-17-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#        with:
#          # Full git history is needed to get a proper list of changed files within `super-linter`
#          fetch-depth: 0
#          path: ~/university-booking-bot

      - name: Lint Code Base
        uses: github/super-linter@v4
        with:
          #repo_token: ${{ secrets.GITHUB_TOKEN }}
          #validate_all_codebase: false
          github_workspace: university-booking-bot

      - name: Build
        run: |
         mvn clean package -Dmaven.test.skip=true

      - name: Test
        run: |
           mvn test

