name: CI/CD

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: "localhost:9000"

on:
  push:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        uses: maven:3.8.3-openjdk-17-slim
        run: |
          cd university-booking-bot
          mvn clean package -Dmaven.test.skip=true

      - name: Save Jar Artifact
        uses: actions/upload-artifact@v2
        with:
          name: JAR
          path: university-booking-bot/target/*.jar
