name: CI/CD

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: "localhost:9000"

on:
  push:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        uses: maven:3.8.3-openjdk-17-slim
        with:
          run: |
            cd university-booking-bot
            mvn clean package -Dmaven.test.skip=true

      - name: Test
        uses: maven:3.8.3-openjdk-17-slim
        with:
          run: |
            cd university-booking-bot
            mvn test

      - name: Install SonarQube Scanner
        run: |
          chmod +x sonar_install || true
          ./sonar_install || true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: SonarQube Analysis
        run: |
          cd university-booking-bot
          mvn verify sonar:sonar -Dsonar.projectKey=university-booking-bot -Dsonar.projectName='university-booking-bot'
