name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: university-booking-bot

      - name: Lint Code Base
        uses: github/super-linter@v4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          validate_all_codebase: false
          github_workspace: university-booking-bot

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          cd university-booking-bot
          apt-get update && apt-get install -y maven
          mvn clean package -Dmaven.test.skip=true
          mvn test

