name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  SuperLint:
    runs-on: ubuntu-latest

    container:
      image: maven:3.8.3-openjdk-17-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: university-booking-bot

      - name: Lint Code Base
        uses: github/super-linter@v4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          validate_all_codebase: false
          github_workspace: university-booking-bot

      - name: Build
        run: |
          mvn clean package -Dmaven.test.skip=true
          
      - name: Test
        run: |
          mvn test
