name: CI/CD

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: "localhost:9000"

on:
  push:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    container:
      image: maven:3.8.3-openjdk-17-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          path: ~/university-booking-bot/*

      - name: Lint Code Base
        uses: github/super-linter@v4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          validate_all_codebase: false
          github_workspace: ${{ github.workspace }}/university-booking-bot

      - name: Build
        run: |
          cd university-booking-bot
          mvn clean package -Dmaven.test.skip=true

      - name: Test
        run: |
          cd university-booking-bot
          mvn test

      - name: Install SonarQube Scanner
        run: |
          chmod +x sonar_install || true
          ./sonar_install || true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: SonarQube Analysis
        run: |
          cd university-booking-bot
          mvn verify sonar:sonar -Dsonar.projectKey=university-booking-bot -Dsonar.projectName='university-booking-bot'

